---
branches:
  - 2.1.0
projects:
  MultiWorld:
    path: ''
    icon: icon.png
    libs:
      Commando:
        src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
      libpmform:
        src: CzechPMDevs/libpmform/libpmform
        version: ^1.1.0
      VanillaGenerator:
        src: CzechPMDevs/VanillaGenerator/VanillaGenerator
        version: ^0.0.6
    lint:
      phpstan: false
...
