---
branches:
  - master
  - feature/pm-3.20.0
  - feature/pm-4.0.0
  - feature/generators
projects:
  MultiWorld:
    path: ""
    icon: icon.png
    libs:
      libpmform:
        src: CzechPMDevs/libpmform/libpmform
        version: ^1.0.1
    lint:
      phpstan: false
      syntaxError: false
...
