name: MultiWorld
author: CzechPMDevs
authors: [ VixikCZ, fuyutsuki, kaliiks ]
api: 4.0.0
version: 1.6.0-beta2
main: czechpmdevs\multiworld\MultiWorld
description: Plugin that manage with worlds
website: https://github.com/CzechPMDevs/MultiWorld
mcpe-protocol: [ 440, 448 ]
extensions:
  Core: '>=7.4'

permissions:
  mw.cmd:
    description: Permission for /multiworld
    default: op
  mw.cmd.help:
    description: Permission for /multiworld help
    default: op
  mw.cmd.create:
    description: Permission for /multiworld create
    default: op
  mw.cmd.teleport:
    description: Permission for /multiworld teleport
    default: op
  mw.cmd.list:
    description: Permission for /multiworld list
    default: op
  mw.cmd.load:
    description: Permission for /multiworld load
    default: op
  mw.cmd.unload:
    description: Permission for /multiworld unload
    default: op
  mw.cmd.delete:
    description: Permission for /multiworld delete
    default: op
  mw.cmd.update:
    description: Permission for /multiworld update
    default: op
  mw.cmd.info:
    description: Permission for /multiworld info
    default: op
  multiworld.command.gamerule:
    description: Permission for /multiworld gamerule
    default: op
  mw.cmd.manage:
    description: Permission for /multiworld manage
    default: op
  mw.cmd.rename:
    description: Permission for /multiworld rename
    default: op
  mw.cmd.duplicate:
    description: Permission for /multiworld duplicate
    default: op